---
- name: create external net
  shell: . /opt/admin-openrc.sh; \
         neutron net-show ext-net || \
         neutron net-create ext-net --router:external \
                                    --provider:physical_network external \
                                    --provider:network_type flat
  run_once: yes

- name: create external subnet
  shell: . /opt/admin-openrc.sh; \
         neutron subnet-show ext-subnet || \
         neutron subnet-create ext-net {{ EXTERNAL_NETWORK_CIDR }} --name ext-subnet \
           --allocation-pool start={{ FLOATING_IP_START }},end={{  FLOATING_IP_END }} \
           --disable-dhcp --gateway {{ EXTERNAL_NETWORK_GATEWAY }}
  run_once: yes

- name: create external router
  shell: . /opt/admin-openrc.sh; \
         neutron router-show router-ext || \
         neutron router-create router-ext
  run_once: yes

- name: set external router gateway
  shell: . /opt/admin-openrc.sh; \
         neutron router-gateway-set router-ext  ext-net
  run_once: yes
